### ISSUE TITLE
[Domain] Domain types are restrained to some basic type

### ISSUE THREAD

**Issue by c3dr0x** [KleeGroup/kinetix#23]
I need to store geographic position in SQLServer and therefore to use the `System.Data.Entity.Spatial.DbGeography` type.

So i need to create a Domain for it as follow:

```c#
        /// <summary>
        /// Domain DO_GEOGRAPHY.
        /// </summary>
        [Domain("DO_GEOGRAPHY")]
        public DbGeography Geography { get; set; }
```

But the domain don't allow to do it because of the following code inside its constructor:
https://github.com/KleeGroup/kinetix/blob/master/Kinetix/Kinetix.ComponentModel/Domain.cs#L83

What it is the purpose of this restriction ?

**Comment by c3dr0x** [comment]
Hi,

Yes I want to store them as geographic data, and I query them as geographic data.
I want to find all matching data within a range from an origin point.

for example:
```sql
itv_vil.VIL_GEOGRAPHY.STDistance(cmp_vil.VIL_GEOGRAPHY) <= @DISTANCE_MAX
```

Using DbGeography which is the equivalent of the `geography` data type in SQLServer is the solution that I found.

Maybe you have something else ?

**Comment by durandx** [comment]
Yes, I think we can have a better solution than using DbGeography.
This solution imply that database should be used only for storage, and elasticsearch or redis must be used to search.
Using the GeoJSON (RFC 7946) or GeoHash format, we can easily store data in database in a generic way (with multiple database vendors, with multiple framework, with multiple language). Search is also fast and can be combined with existing search with ElasticSearch or Redis. We can even improve our existing search by using a web mapping library that can be used to display results in a map and used as a criteria by using the displayed area as a bounding box...

- What is your use case? 
- Do you think a database search is really mandatory for that ?

**Comment by c3dr0x** [comment]
Yep, I thought of it. I even started this way (using ES). 

But I have other constraints that forces me to do this specific query using BDD and therefore using DbGeography. I don’t only need to search via distances but with other objects, that I cannot translate easily in ES. 

We can talk about it over the phone if needed. But for me it is another subject. 

To answer your worries. I don’t want to hard code DbGeography as an allowed domain type. But extend more generally types to any type we need. There shouldn’t be restriction on it via Domain. Those restriction are already constrained within types handled by the database driver. Kinetix can’t have a say in this.

**Comment by JabX** [comment]
I think that most database vendors follow the OpenGIS specification, which is compatible with basically everything (GeoJSON, ElasticSearch, any kind of language specific library to manipulate spatial data…), so I would be too worried about being tied to a special C# type like DbGeography/DbGeometry for SQL Server, at least for the time being. The specification not only dictates how the data is represented and stored (which is in a binary format for performance), but also the entire surface API, meaning that, much like SQL itself, everything is already a shared standard.

Npgsql (Postgre driver for .NET) has a plugin for spatial data that uses NetTopologySuite (which is the reference library for spatial in the .NET world) instead of specific provider types like DbGeometry. It works very well with EF (both 6 and Core) and there are currently some discussions about extending this behavior for all database drivers in the future, and making NTS the defacto standard library for everything spatial.

Nest only needs a JsonConverter to index in ES any non standard type, and NTS comes with converters for every spatial type (data is stored as GeoJSON in ES).

Sharing the same formats and APIs across all layers (DB, ES, server even on the client if you like) is extremely convenient because it makes it very easy to use the best solution for every problem since you can easily manipulate the spatial data everywhere. And they are natively all compatible with each other, so it's pretty much as good as it can be without doing anything special.

In any case, @c3dr0x's request was way less far-reaching that spatial data and allowing arbitrary types in domains can be very useful for a lot of other applications, especially considering the rich possibilities that modern (R)DBMS offer in terms of primitive types that we'd be unable to use if we can't use anything other than strings, number types, booleans, guids and dates/timespans in Kinetix. They can be the only types supported out of the box (with checkers and such), but I don't think there is a point into preventing projects to roll their own if that can offer a better solution to a problem someone is facing.

**Comment by durandx** [comment]
Fixed in develop
